// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BetterScroll: typeof import('./../components/custom/BetterScroll.vue')['default']
    ColumnSetting: typeof import('./../components/TablePro/components/settings/ColumnSetting.vue')['default']
    CountTo: typeof import('./../components/custom/CountTo.vue')['default']
    DarkModeContainer: typeof import('./../components/common/DarkModeContainer.vue')['default']
    DarkModeSwitch: typeof import('./../components/common/DarkModeSwitch.vue')['default']
    EditableCell: typeof import('./../components/TablePro/components/editable/EditableCell.vue')['default']
    Form: typeof import('./../components/FormPro/src/Form.vue')['default']
    HoverContainer: typeof import('./../components/common/HoverContainer.vue')['default']
    IconSelect: typeof import('./../components/custom/IconSelect.vue')['default']
    NaiveProvider: typeof import('./../components/common/NaiveProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemLogo: typeof import('./../components/common/SystemLogo.vue')['default']
    TableAction: typeof import('./../components/TablePro/components/TableAction.vue')['default']
    TablePro: typeof import('./../components/TablePro/TablePro.vue')['default']
    WebSiteLink: typeof import('./../components/custom/WebSiteLink.vue')['default']
  }
}

export {}
